### ISSUE TITLE
Could you provide more documention on the parameters of the config.json

### ISSUE THREAD

**Issue by ChojinDSL** [antrew/btrfs-scrub-scheduler#3]
In the config.json, 
what exactly does "period" mean and what is the possible syntax for "maxDuration"?
What does the "PT" in "PT7H" mean?

**Comment by antrew** [comment]
Thank you for pointing that out! I will change that and document it better.

`period` is the number of days between scrubs. If the last scrub of a filesystem finished less than `period` days ago, the filesystem will not be scrubbed. E.g., `"period": 90` would scrub each filesystem every 3 months.

`maxDuration` is a string that defines the maximum duration of a single scrub run. If the scrub takes longer than `maxDuration`, it will be interrupted and resumed on the next script execution. E.g., `"maxDuration": "PT6H30M"` will cancel the scrub after 6,5 hours.

`maxDuration` can be any string that can be parsed by moment.js as a duration: https://momentjs.com/docs/#/durations/creating/

`maxDuration` can be something like '06:30' or 'PT6H30M' (ISO-8601: 
 https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by antrew** [comment]
Fixed documentation and improved consistency in configuration parameters in this release: https://github.com/antrew/btrfs-scrub-scheduler/releases/tag/v1.1.0
